os: osx
language: generic

env:
  - PYENV_VERSION=3.6.8

before_install: |
  brew outdated pyenv || brew upgrade pyenv
  brew install pyenv-virtualenv
  env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.8
  export PATH="/Users/travis/.pyenv/shims:${PATH}"
  python --version

install:
  - python -m easy_install -U setuptools
  - pip install -r requirements.txt

script:
  - fbs freeze
  - fbs installer

deploy:
  provider: releases
  api_key:
    secure: ukdjEv7VzK2clal62G5yB3nT4teBcUSRwtrala9FA+1CUhnbhaHixrLwfXacqXztvUol1xUtSKlHG0JoWYWjCGHDrAiwjjCkyEdtu2+gCfp380ovaiSeu8DMvTZK6Zs73cifFOJZ20vaHEm8htgzuplxTwddaJt/IAYsnw1lYx3nGJ2XEPUupDQAZ7ScvzhGrdT3KCl9qHw2MCoBSDK9gF98AGCkOZHTie4BFx2HWE+f7eiLhFJbhSWJgY9tjZTqCQAF2cRq6EHsPaGEWkmMKYfRIrJuKVQCYm+TIXzPb9Fm4TfoEJXdEQHMCfve1eJXhI1NYw8Vt4iFoRX+yAwxU6nrZ6Nc7ck1jn2DTZbtfvd1paoR8bKu5eZKCaQgwZNafo1oTxCmOzwsFatg67/+nyc6skswgBXRJzGqEuk9G2p5sJVx1Hot5jEggMelWs0+3qSN7h2JhrnndUwAOQ551/8Knr5rSZQ5D+D4P1tgUfW+tqfIG8hlz9zLupgnU7tOnbDqeKr8+F06jlFmLL+WhChFla7/Mdmg2GqtJdJkV/R5LvrFihPzp2ZP6uH9FuJqa8T/2cOv7Pa/zSIqpm4TrceFS7EiY757QUgcewhgIB43D/L9g6LP8t0GMnv4jt/x9gJQgJDk8cMBRqgfNM3bovXW3Lzu5MglrqEP8DzlaqQ=
  file_glob: true
  file: target/*.dmg
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: JeziL/RadUI