os: osx
language: generic

env:
  - PYENV_VERSION=3.6.8

before_install: |
  brew outdated pyenv || brew upgrade pyenv
  brew install pyenv-virtualenv
  env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.8
  export PATH="/Users/travis/.pyenv/shims:${PATH}"
  python --version

install:
  - python -m easy_install -U setuptools
  - pip install -r requirements.txt

script:
  - fbs freeze
  - fbs installer

deploy:
  provider: releases
  api_key:
    secure: XjXKTZ5Rwb9oPi9+AP6RJRjx3rGw93XB3IdmKp+z5YX/2/1oGLW1p8wNF6N3U2bL0zZ7XIzzUWtDapus4a0fzB98oTG7W4kw0DgZYZ2zL5lLeOM72hLKGTWDS09HJh6KPvhPCPy/XQp0Mofu6lekGM5YhtMv68i2nLxC2Jg8+ngfs/Jntz5ZqCSe+KzBj4ewYMF0FfMIty4mrg5inZ5Ss0FN0zbeEasdbesQj64epALN3D8hg4qgULsJsYJ71MEfZLmfNpz0zxx1hV48Ehgd2DSB/mVJ35lVkT/REEBWuqj4NmlcfTWr7TmP2Lxit0Raytslqui9JLWN3wku1X0oToIooJJlKVp172eICCXtL4/9TmK7GXgwO0FXeT+y5PUNaSMyb3OrwnsWoCAYBvGNfYO3RmJJHMvGmTj1q235x+HxaYHjzQuNbh2AAblLY8+8Z5Ggr+BX/XwnAFRqA5ZcIXWC6bnNAhh3Q+4f59bAvEP37E3gYmVSXalOhoh/bmQRJHhZC9udRkTo4XiHogPgjbJH/J8qxa0JXsRgdHsF2pgCZ+OdhH2JIzSjsrAF/uqzWoKb6u/voe30UvdG6G2eW6mmLOrfOv81B9SH92lWBJcN6VTN/JE18byElTCTZsV+i1eSb8wtu1jJ1Fm8in1wpAjQsrQczk+U9YavuUqiHjw=
  file_glob: true
  file: target/*.dmg
  skip_cleanup: true
  overwrite: true
  on:
    tags: true